#!/bin/sh

# Load MGI Config

if [ "${MGICONFIG}" = "" ]
then
    MGICONFIG=/usr/local/mgi/live/mgiconfig
    export MGICONFIG
fi

. ${MGICONFIG}/master.config.sh

# Play around with JAVA_HOME

JAVA_HOME=/usr/jdk/jdk1.6.0_07/
CLASSPATH=$CLASSPATH:./qs_indexer.jar:/usr/local/mgi/live/lib/java/core.jar:/usr/local/lucene-2.3.2/lucene-core-2.3.2.jar:/usr/local/lucene-2.3.2/contrib/snowball/lucene-snowball-2.3.2.jar:/usr/local/mgi/live/lib/java/qs_commons.jar:/usr/local/apache-log4j-1.2.15/log4j-1.2.15.jar

export CLASSPATH

echo $CLASSPATH


###########################
# Make the Marker Indexes
###########################

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerInexact/index/ g

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerDisplay/index/ gd

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerExact/index/ ge

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerAccID/index/ ga

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerSymbol/index/ gs

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerVocabExact/index/ gve

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /data/searchtool/build/markerVocabDag/index/ gvd

java -Xms128m -Xmx512m org.jax.mgi.index.index.MakeIndex /export/valinor/index/markerVocabAccID/index/ gva


